version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.1.8                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    dhealth:
        mem_limit: 768MB
#        image: atsanna/codeigniter4:latest
        image: atsanna/codeigniter4:v4.1.8-php7.4
#        image: atsanna/codeigniter4:v4.1.8-php8.0
        container_name: 'dhealth'
        ports:
          - 80:80
        links:
          - dhealth_mysql
        volumes:
          - ./localfolder/www:/var/www/html

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    dhealth_mysql:
        mem_limit: 256MB
        image: mariadb:10.5.5
        container_name: 'dhealth_mysql'
        ports:
          - 3306:3306
        volumes:
          - ./localfolder/mysql:/var/lib/mysql
          - ./localfolder/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: dhealth
          MYSQL_USER: dhealth
          MYSQL_PASSWORD: dhealth

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    dhealth_phpmyadmin:
        mem_limit: 256MB
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'dhealth_phpmyadmin'
        links:
          - dhealth_mysql
        environment:
          PMA_HOST: dhealth_mysql
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - ./localfolder/sessions:/sessions
